// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzfhbugqnlxskheaudqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6ZmhidWdxbmx4c2toZWF1ZHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTc5MTYsImV4cCI6MjA1OTgzMzkxNn0.WzemCTre683ZG_BLze4PxCZWQrsxF1W9driSHsj7O1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);